/*
       --MOUSE--
    ONCLICK - APENA UM CLIQUE;
    ONDBLCLICK - CLIQUE DUPLO;
    ONMOUSEUP - QUANDO SOLTA O CLIQUE DO BOTÃO;
    ONMOUSEOVER - QUANDO O MOUSE PASSA POR CIMA;
    ONMOUSEOUT - QUANDO O MOUSE DA DO ELEMENTO;


    --TECLADO--
    ONKEYDOWN - DIGITAR QUALQUER TECLA;
    ONKEYPRESS - MANTER A TECLA PRECIONADA;
    ONKEYUP - QUANDO A TECLA É LIBERADA;


    --JANELA--
    ONRESIZE - QUANDO O TAMANHO DA TELE É REDIMESIONADO;
    ONSCROLL- QUANDO A TELA É ROLADA;


    --FOMRULÁRIO--
    ONFOCUS - QUANDO O INPUT ESTÁ EM FOCO;
    ONBLUR - QUANDO O ELEMENTO PERDE O FOCO;
    ONCHANGE- QUANDO O ELEMENTO É MODIFICADO;
*/